spring:
  # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  # Corresponding environment variables must be set
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # https://github.com/spring-projects/spring-boot/issues/12007
        jdbc:
          lob:
            non_contextual_creation: true
